# Generated by Django 2.1.5 on 2019-06-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(default='', max_length=255)),
                ('article_description', models.CharField(default='', max_length=255)),
                ('article_addtime', models.DateTimeField(auto_now_add=True)),
                ('article_content', models.TextField()),
                ('article_praise_num', models.IntegerField(default=0)),
                ('article_is_recommend', models.IntegerField(default=0, verbose_name='0:不推荐,1：推荐')),
                ('article_clicknum', models.IntegerField(default=0)),
                ('article_img', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(default='', max_length=255)),
                ('comment_addtime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(default='', max_length=100)),
                ('member_tel', models.CharField(default='', max_length=11)),
                ('member_email', models.CharField(default='', max_length=60)),
                ('member_nickname', models.CharField(default='', max_length=60)),
                ('member_pwd', models.CharField(default='', max_length=60)),
                ('Praise_list', models.ManyToManyField(to='blog.Article')),
                ('praise', models.ManyToManyField(to='blog.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('web_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(default='', max_length=100)),
                ('web_content', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('word_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('word_content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('word_addtime', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('word_img', models.CharField(max_length=255, verbose_name='评论头像图片')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Member'),
        ),
        migrations.AddField(
            model_name='article',
            name='membered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Member'),
        ),
    ]
