# Generated by Django 2.1.5 on 2019-07-12 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conservator',
            fields=[
                ('conservator_id', models.AutoField(primary_key=True, serialize=False)),
                ('conservator_name', models.CharField(max_length=60, verbose_name='用户名')),
                ('conservator_tel', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='联系方式')),
                ('conservator_email', models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='邮箱')),
                ('conservator_province', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='省份')),
                ('conservator_city', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='市')),
                ('conservator_area', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='区')),
                ('conservator_addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('conservator_pwd', models.CharField(max_length=100, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=60, null=True, verbose_name='菜单名称')),
                ('menu_path', models.CharField(blank=True, max_length=60, null=True, verbose_name='菜单路径')),
                ('pid', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='back.Menu', verbose_name='关联的权限')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=60, null=True, verbose_name='权限名')),
                ('permission_rule', models.CharField(blank=True, max_length=100, null=True, verbose_name='规则')),
                ('menu', models.ForeignKey(blank=True, help_text='null表示不是菜单(为空的),非null表示的是二级的菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='back.Menu', verbose_name='所属的菜单')),
                ('pid', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='back.Permission', verbose_name='关联的权限')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=60, verbose_name='角色名')),
                ('role_access', models.CharField(blank=True, help_text='不同的角色有不同的权限', max_length=60, null=True, verbose_name='可以访问的权限')),
                ('conservator', models.ManyToManyField(to='back.Conservator')),
            ],
        ),
    ]
